steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/100963062/sarvesh-100963062/assignment2:${SHORT_SHA}', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/100963062/sarvesh-100963062/assignment2:${SHORT_SHA}']

  # Step 3: Deploy the Docker image to Cloud Run using gcloud CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'assignment2'
      - '--image'
      - 'us-central1-docker.pkg.dev/100963062/sarvesh-100963062/assignment2:${SHORT_SHA}'
      - '--region'
      - 'us-central1'

images:
  - 'us-central1-docker.pkg.dev/100963062/sarvesh-100963062/assignment2:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY  # Corrected logging option

# Define the artifact registry for Docker images
artifacts:
  images:
    - 'us-central1-docker.pkg.dev/100963062/sarvesh-100963062/assignment2:${SHORT_SHA}'
