steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}',
      '.'
    ]

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}'
    ]

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET