steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}',
      '.'
    ]

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'sarvesh-100963062-services',
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/sarvesh-100963062/app:$COMMIT_SHA',
           '--region', 'us-central1', '--platform', 'managed']

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/sarvesh-100963062/assignment2:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET