steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sarvesh-100963062/todo-app:$COMMIT_SHA', '.']
    id: 'Build Docker image'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sarvesh-100963062/todo-app:$COMMIT_SHA']
    id: 'Push Docker image'

  # Step 3: Deploy to Cloud Run (continuous deployment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'todo-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sarvesh-100963062/todo-app:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
    id: 'Deploy to Cloud Run'

# Optionally set the logs bucket (for storing build logs)
options:
  logging: 'REGIONAL_USER_OWNED_BUCKET'
  substitutionOption: 'ALLOW_LOOSE'

# Cloud Build trigger configuration
timeout: 600s
